b9/b9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('user.urls')),
    path('', include('post.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

b9/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.post_create, name='post_create'),
    path('<int:post_id>/update/', views.UpdatePost.as_view(), name='post_update'),
    path('<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('<int:post_id>/', views.detail_post, name='detail_post'),
    path('<int:post_id>/delete', views.delete_post, name='delete_post'),
    path('<int:post_id>/comment/add/', views.add_comment, name='add_comment'),
    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그 내 문자열로 들어가면
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # 페이지 검색 기능
    path('post/search/',views.PostList.as_view(), name='post_searched')
    # path('like_notifications/', views.like_notifications, name='like_notifications'),
]

b9/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path("", views.home, name='codeshare'),
    path("index", views.index, name='index'),
    path("NBcamp[-1]/", views.b_9, name='b_9'),
    path("signup/", views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('follows/', views.FollowList.as_view(), name='follow'),
    path('@<str:username>/follow/', views.add_or_sub_follower, name='following'),
    path('@<str:username>/update/', views.user_mypage_update, name='mypage_update'),
    path('@<str:username>/', views.user_mypage, name='mypage'),
    path('search/', views.UserList.as_view(), name='search'),

]

b9/b9/post/models.py
from django.db import models
from django.contrib.auth.models import User
from user.models import User
from django.utils import timezone

# Create your models here.
class PostModel(models.Model):
    class Meta:
        db_table = "Post"

    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    post = models.TextField()
    photo = models.ImageField(blank=True, upload_to="media/%Y/%m/%d")
    like_users = models.ManyToManyField(User, related_name='like_posts')
    like_count = models.IntegerField(blank=True, null=True,default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    contant = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    # def __str__(self): 
    #     return self.name
    
    
#asdasd

b9/post/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):
    class Meta:
        db_table = "Post"

    writer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    post = models.TextField()
    photo = models.ImageField("포스트이미지",upload_to="post_photo/%Y/%m/%d" , blank=True, null=True)
    like_users = models.ManyToManyField(get_user_model(), related_name='like_articles')
    like_count = models.IntegerField(blank=True, null=True,default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    

class Comment(models.Model):
    content = models.TextField("댓글 작성")
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content



    

b9/post/forms.py
from django import forms
from .models import Post,Comment
from django_summernote.widgets import SummernoteWidget
# 글을 작성하는 폼입니다. 위젯으로 작성공간 만들어줬습니다.
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'post', 'photo', 'tags',]
        widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control mt-2'}),
        'post': SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px'}}),
        'photo': forms.ClearableFileInput(attrs={'class': 'form-control mt-2'}),
        'tags' : forms.TextInput(attrs={'class': 'form-control mt-2', 'placeholder': '콤마(,)로 구분해주세요'}),
        }
        labels = {
            'title': '제목',
            'post': '내용',
            'photo': '사진',
            'tags': '태그',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '400px'}}),
        }

b9/post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from user.models import Profile, User
from .forms import PostForm, CommentForm
from django.http import HttpResponse
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.views.generic import ListView, TemplateView
from django.db.models import Q
# Create your views here.

# 메인 페이지


# 글 작성 view


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        user = request.user
        tags = request.POST.get('tags', '').split(',')

        if form.is_valid():
            post = Post.objects.create(
                writer=user,
                title=form.cleaned_data.get('title'),
                post=form.cleaned_data.get('post'),
                photo=form.cleaned_data.get('photo'),
            )
            for tag in tags:
                tag = tag.strip()
                if tag != '':
                    post.tags.add(tag)
            post.save()
            return redirect('user:index')
    if request.method == 'GET':
        form = PostForm()
    return render(request, 'post/post_create.html', {'form': form})


class TagCloudTV(TemplateView):
    template_name = 'taggit/tag_cloud_view.html'

# 태그가 있으면 태그를 보여주겠다.


class TaggedObjectLV(ListView):
    template_name = 'taggit/tag_with_post.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context


class UpdatePost(UpdateView):
    model = Post
    form_class = PostForm
    pk_url_kwarg = 'post_id'
    template_name = 'post/post_create.html'

    def get_success_url(self):
        return reverse_lazy('post:detail_post', kwargs={'post_id': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['update'] = True
        return context


# sdfsdf
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('post:detail_post', post_id)
    return redirect('post:detail_post', post_id)


@login_required
def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    print(comment)
    if comment.author != request.user:
        return redirect('post:detail_post', comment.post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        print(form.fields['content'])
        print(form.errors)
        if form.is_valid():
            print('valid')
            form.save()
            return redirect('post:detail_post', comment.post_id)
    else:
        form = CommentForm(instance=comment)
    return redirect('post:detail_post',  comment.post_id)


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    print(comment.post_id)
    if comment.author != request.user:
        return redirect('post:detail_post', comment.post_id)
    comment.delete()
    return redirect('post:detail_post', comment.post_id)


@login_required
def toggle_like(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)
        user = request.user
        if post.like_users.filter(pk=user.pk).exists():
            post.like_users.remove(user)
            post.like_count -= 1
            post.save()
        else:
            post.like_users.add(user)
            post.like_count += 1
            post.save()
        return redirect('user:index')
    return redirect('user:login')


# #현재 사용자가 작성한 게시글에 대한 좋아요 알림을 보여주는 함수
# @login_required
# def like_notificatons(request):
#     likes = Like.objects.filter(post__writer=request.user).order_by('-created_at')
#     context = {'likes':likes}
#     return render(request, 'post/like_notifications.html', context)



@login_required
def detail_post(request, post_id):
    if request.method == 'GET':
        user = request.user.is_authenticated
        if user:
            post_detail = Post.objects.get(id=post_id)
            post_detail.comment_count = Comment.objects.filter(post_id = post_id).count()
            # all_comment = Comment.
            commentform = CommentForm()
            all_comment = Comment.objects.filter(post_id=post_id)
            return render(request, 'post/detail.html', {'post_detail': post_detail, 'all_comment': all_comment, 'commentform': commentform})
        else:
            return redirect('login')
        
def delete_post(request, post_id):
    user = request.user
    post = Post.objects.get(id=post_id)
    if user == post.writer:
        post.delete()
        return redirect('user:index')

class PostList(ListView):
    model = Post
    template_name = 'post/post_searched.html'
    context_object_name = 'posts_searched'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('query', '')
        if query:
            return self.model.objects.filter(Q(title__icontains=query) |
                                             Q(post__icontains=query)
                                             ).distinct().order_by('-created_at')
        else:
            return self.model.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query', '')
        return context

b9/templates/post/detail.html
<!-- templates/tweet/main.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Main -->
    <div id="main">

        <!-- Post -->
        <article class="post">
            <header>
                <div class="title">
                    <h2>{{ post_detail.title }}</h2>
                    {% if post_detail.tags.all %}
                        {% for tag in post_detail.tags.all %}
                            <a style="font-size: small"
                               href="{% url 'post:tagged_object_list' tag.name %}">
                                <span> #{{ tag.name }}&nbsp; </span>
                            </a>
                        {% endfor %}
                        -<a style="font-size: small"
                            href="{% url 'post:tag_cloud' %}">TagCloud</a>
                    {% endif %}
                </div>
                <div class="meta">
                    <time class="published">{{ post_detail.created_at }}</time>
                    <a href="{% url 'user:mypage' post_detail.writer.username %}"><span
                            class="name">{{ post_detail.writer.last_name }} {{ post_detail.writer.first_name }}</span>
                        <img src="{% static 'images/avatar.jpg' %}" alt=""/></a>
                </div>
            </header>
            {% if post_detail.photo.url != None %}
                <span class="image featured" style="text-align: center;"><img src="{{ post_detail.photo.url }}" alt=""
                                                                              style="max-height: 500px; height: auto; width: auto; display: inline-block;"/></span>
            {% endif %}
            <div style="margin: 20px 0px;">{{ post_detail.post|safe }}</div>
            <footer>
                <ul class="stats">
                    <li><a href="{% url 'user:index' %}">back</a></li>
                    {% if user in post_detail.like_users.all %}
                        <li><a href="{% url 'post:toggle_like' post_detail.id %}"
                               class="icon solid fa-heart" style="color:#ff00a0">{{ post_detail.like_count }}</a>
                        </li>
                    {% else %}
                        <li><a href="{% url 'post:toggle_like' post_detail.id %}"
                               class="icon solid fa-heart"
                               style="color: rgba(160, 160, 160, 0.5);">{{ post_detail.like_count }}</a></li>
                    {% endif %}
                    <li><a href="{% url 'post:detail_post' post_detail.id %}" class="icon solid fa-comment">{{ post_detail.comment_count }}</a></li>
                    {% if post_detail.writer_id == user.username %}
                        <li><a href="{% url 'post:post_update' post_detail.id %}">수정</a></li>
                        <li><a href="{% url 'post:delete_post' post_detail.id %}">삭제</a></li>
                    {% endif %}
                </ul>
            </footer>
            <form action="{% url 'post:add_comment' post_detail.id %}" method="post">
                {% csrf_token %}
                {{ commentform.as_p }}
                <button type="submit">댓글 등록</button>
            </form>
        </article>


        {% for comment in all_comment %}
            <div class="sh_comment_box_custom post">
                <header style="border-bottom: solid 1px #F3CB27; margin: -3em 0 -1em 0;">
                    <div class="title">
                        <h3 class="mb-1 sh_font_2">{{ comment.content|safe }}</h3>
                        <div style="float: right;">
                            {% if comment.created_at != comment.updated_at %}
                                (수정됨)
                            {% endif %}
                            {% if comment.author == user %}
                                <a onclick="toggleCommentEditForm('{{ comment.id }}')">수정</a>
                                <a href="{% url 'post:delete_comment' comment.id %}">삭제</a>
                                </div>
                                <div id="comment-edit-form-{{ comment.id }}" style="display: none; margin-top: 16px;">
                                    <form method="POST" action="{% url 'post:edit_comment' comment.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="comment_id" value="{{ comment.id }}">
                                        <textarea name="content" rows="3"
                                                  style="margin-bottom: 16px;"></textarea>
                                        <button type="submit">등록</button>
                                        <button type="button" onclick="toggleCommentEditForm('{{ comment.id }}')">취소
                                        </button>
                                    </form>
                                </div>
                            {% endif %}
                    </div>
                    <div class="meta">
                        <h3 class="mb-2">{{ comment.author.last_name }} {{ comment.author.first_name }}
                        </h3>
                        <p class="sh_date_custom">{{ comment.created_at }}</p>
                    </div>
                </header>
            </div>
        {% endfor %}
    </div>


    <script>
        function toggleCommentEditForm(commentId) {
            var form = document.getElementById('comment-edit-form-' + commentId);
            if (form.style.display === 'none') {
                form.style.display = 'block';
            } else {
                form.style.display = 'none';
            }
        }
    </script>



{% endblock %}

b9/templates/post/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글 작성하기</h5>
    <form method="POST" class="post-form my-3" action="{% if update %}{% url 'post:post_update' post_id=post.id %}{% else %}{% url 'post:post_create' %}{% endif %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}

        <div style="text-align: center">
            <button type="submit" class="button large next">{% if update %}수정{% else %}글 쓰기{% endif %}</button>
            <a href="{% url 'user:index' %}" class="button large next">취소</a>
        </div>
    </form>
</div>
<script src="{% static 'django_summernote/summernote.js' %}"></script>
<script>
    $(function() {
        $('#id_content').summernote();
    });
</script>

{% endblock %}

b9/templates/post/post_searched.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- templates/tweet/home.html -->
    <div class="container timeline-container">
        <div class="row"></div>
        <!-- 오른 쪽 컬럼-->
        <div class="col-md-7" style="width: auto">
         <!-- 포스트 검색기능-->
                <section>
                    <form method="GET" action="{% url 'post:post_searched' %}" class="sh_search_home">
                        <input type="text" name="query" placeholder="{{ request.GET.query }}" value="{{ request.GET.query }}">
                        <button type="submit">Post Search</button>
                    </form>
                </section>
            <hr>
            <!-- 작성 된 글이 나오는 곳 -->
            {% if request.GET.query %}
                <h1> 검색하신 '{{ request.GET.query }}' 게시글 정보입니다. </h1>
                <br>
                {% if posts_searched %}
                    {% for post in posts_searched %}
                        <article class="post">
                            <header>
                                <div class="title">
                                    <h2>{{ post.title }}</h2>
                                    {% if post.tags.all %}
                                        {% for tag in post.tags.all %}
                                            <a style="font-size: small"
                                               href="{% url 'post:tagged_object_list' tag.name %}">
                                                <span> #{{ tag.name }}&nbsp; </span>
                                            </a>
                                        {% endfor %}
                                        -<a style="font-size: small"
                                            href="{% url 'post:tag_cloud' %}">TagCloud</a>
                                    {% endif %}
                                </div>
                                <div class="meta">
                                    <time class="published"
                                          datetime="{{ post.created_at }}">{{ post.created_at|timesince }}
                                        전
                                    </time>
                                    <a href="{% url 'user:mypage' post.writer.username %}" class="author"><span class="name">{{ post.writer.username }}</span></a>
                                </div>
                            </header>
                            {% if post.photo %}
                                <a href="{% url 'post:detail_post' post.writer.username %} " class="image featured"><img src="{{ post.photo.url }}" alt=""/></a>
                            {% endif %}
                            <p>{{ post.post|safe }}</p>
                            <footer>
                                <ul class="actions">
                                    <li><a href="{% url 'post:detail_post' post.id %}" class="button large">Continue Reading</a></li>
                                </ul>
                                <ul class="stats">
                                    {% if user in post.like_users.all %}
                                        <li><a href="{% url 'post:toggle_like' post.id %}"
                                               class="icon solid fa-heart"
                                               style="color:#ff00a0">{{ post.like_count }}</a></li>
                                    {% else %}
                                        <li><a href="{% url 'post:toggle_like' post.id %}"
                                               class="icon solid fa-heart"
                                               style="color: rgba(160, 160, 160, 0.5);">{{ post.like_count }}</a></li>
                                    {% endif %}
                                    <li><a href="#" class="icon solid fa-comment"
                                           style="color: rgba(160, 160, 160, 0.5);">128</a></li>
                                </ul>
                            </footer>
                        </article>
                    {% endfor %}
                    <hr>
                    <ul class="actions pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page=
                                    {{ page_obj.previous_page_number }}{% if query %}&query={{ query }}{% endif %}"
                                   class="button large previous">Previous
                                Page</a></li>
                        {% else %}
                            <li><a href=" " class="disabled button large previous">Previous Page</a></li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li><a href="?page=
                                    {{ page_obj.next_page_number }}{% if query %}&query={{ query }}{% endif %}"
                                   class="button large next">Next Page</a></li>
                        {% else %}
                            <li><a href=" " class="disabled button large next">Next Page</a></li>
                        {% endif %}
                    </ul>
                {% else %}
                    <h1> 검색 결과가 없습니다. </h1>
                {% endif %}
            {% else %}
                <h1> 찾고 있는 게시글을 검색창에 입력해주세요. </h1>
            {% endif %}
            <!-- 페이지 선택 -->

        </div>

    </div>
{% endblock %}