b9/b9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('user.urls')),
    path('', include('post.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

b9/b9/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'user'

urlpatterns = [
    path("",views.index,name='index'),
    path("signup/", views.user_signup,name='signup'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/',views.user_logout,name='profile'),
]

b9/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.post_create, name='post_create'),
    path('<int:post_id>/update/', views.UpdatePost.as_view(), name='post_update'),
    path('<int:post_id>/like/', views.toggle_like, name='toggle_like'),
    path('<int:post_id>/', views.detail_post, name='detail_post'),
    path('<int:post_id>/delete', views.delete_post, name='delete_post'),
    path('<int:post_id>/comment/add/', views.add_comment, name='add_comment'),
    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # 태그 내 문자열로 들어가면
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # 페이지 검색 기능
    path('post/search/',views.PostList.as_view(), name='post_searched')
    # path('like_notifications/', views.like_notifications, name='like_notifications'),
]

b9/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path("", views.home, name='codeshare'),
    path("index", views.index, name='index'),
    path("NBcamp[-1]/", views.b_9, name='b_9'),
    path("signup/", views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('follows/', views.FollowList.as_view(), name='follow'),
    path('@<str:username>/follow/', views.add_or_sub_follower, name='following'),
    path('@<str:username>/update/', views.user_mypage_update, name='mypage_update'),
    path('@<str:username>/', views.user_mypage, name='mypage'),
    path('search/', views.UserList.as_view(), name='search'),

]

b9/b9/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(
        "ID", max_length=24, unique=True, primary_key=True,)

    def __str__(self):
        return f'{self.username} : {self.last_name}{self.first_name}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscript = models.CharField("유저소개문(짧게)", max_length=200)
    profile_image = models.ImageField("유저이미지")
    follows = models.ManyToManyField(
        'self', through='Follow', related_name='follwers', symmetrical=False)


class Follow(models.Model):
    follower = models.ForeignKey(
        Profile, related_name="following", on_delete=models.CASCADE)
    followee = models.ForeignKey(
        Profile, related_name="followed_by", on_delete=models.CASCADE)

b9/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(
        "ID", max_length=24, unique=True, primary_key=True,)

    def __str__(self):
        return f'{self.username} : {self.last_name}{self.first_name}'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscript = models.CharField("유저소개문(짧게)", max_length=200, blank=True)
    profile_image = models.ImageField("유저이미지", upload_to='profile_images/', blank=True, null=True)
    follows = models.ManyToManyField(
        'self', through='Follow', related_name='follwers', symmetrical=False)
    
    def __str__(self):
        return f'{self.user.username}'

    def is_following(self, target_profile):
        return self.following.filter(followee=target_profile).exists()


class Follow(models.Model):
    follower = models.ForeignKey(
        Profile, related_name="following", on_delete=models.CASCADE)
    followee = models.ForeignKey(
        Profile, related_name="followed_by", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.follower} 팔로우-> {self.followee}'
    

b9/b9/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model


class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'last_name',
                  'first_name', 'password1', 'password2')

b9/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile


class UserCreateForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'last_name',
                  'first_name', 'password1', 'password2']


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['subscript','profile_image']

b9/b9/user/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages
from .forms import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.


def index(request):
    return render(request, "user/user.html")


def user_signup(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:login')
        else:
            messages.error(request, form.errors)
            messages.error(request, form.non_field_errors())

    else:
        form = UserCreateForm()
    return render(request, 'user/signup.html', {"form": form})


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request, "user is None")
        else:   
            messages.error(request, "form is not valid")
            print("Form Errors: ", form.errors)
            print("Non-field Errors: ", form.non_field_errors())
    else:
        form = AuthenticationForm(request)
    return render(request, 'user/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home')

@login_required
def follow_list(request):
    follows = request.user.Profile.follows.all()
    return render(request,'user/follow_list.html',{'follows':follows})

@login_required
def add_or_sub_follower(request,uid):
    target = get_object_or_404('Profile',pk=uid)
    user_profile = request.user.Profile
    
    if user_profile.follows.filter(id=target.id).exist():
        user_profile.follows.remove(target)
    else:
        user_profile.follows.add(target)

    return 

b9/user/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import *
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from post.models import Post,Comment
from django.views.generic import ListView
from django.db.models import Q
from django.core.paginator import Paginator


def b_9(request):
    return render(request, "NBcamp[-1].html")


# Create your views here.
def home(request):
    return render(request, "Codeshare.html")


def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    for post in post_list:
        post.comment_count = Comment.objects.filter(post_id = post.id).count()
    paginator = Paginator(post_list, 4)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    user = request.user
    if user.is_authenticated:
        following_users = user.profile.follows.all()
        if following_users:
            following_ids = [u.user.pk for u in following_users]
            followings = Post.objects.filter(writer__in=following_ids)
        else:
            followings = Post.objects.none()
    else:
        followings = None
    context = {
        'posts': posts,
        'followings': followings.order_by('-created_at') if followings else None
    }

    return render(request, "user/index.html", context)


def user_signup(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('user:login')
        else:
            messages.error(request, form.errors)
            messages.error(request, form.non_field_errors())

    else:
        form = UserCreateForm()
    return render(request, 'user/signup.html', {"form": form})


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('user:index')
            else:
                messages.error(request, "user is None")
        else:
            messages.error(request, "form is not valid")
            print("Form Errors: ", form.errors)
            print("Non-field Errors: ", form.non_field_errors())
    else:
        form = AuthenticationForm(request)
    return render(request, 'user/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return redirect('user:login')


@login_required
def user_mypage(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    profile = Profile.objects.get(user=user)
    all_mypost = Post.objects.filter(writer=username).order_by('-created_at')

    for post in all_mypost:
        post.commentcount = Comment.objects.filter(post_id = post.id).count()
    # likes = Like.objects.filter(user=username)

    if request.user.username == username:
        # 현재 로그인한 사용자와 페이지 주인이 같은 경우
        user_profile = profile
        is_following = None
    else:
        # 다른 사용자의 페이지인 경우 해당 사용자의 프로필 정보를 전달
        user_profile = Profile.objects.get(user=user)
        is_following = request.user.profile.is_following(profile)

    return render(request, 'user/mypage.html', {'profile': profile, 'posts': all_mypost, 'user_profile': user_profile, 'is_following': is_following})


@login_required
def user_mypage_update(request, username):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        profileform = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if form.is_valid() and profileform.is_valid():
            form.save()
            profileform.save()
            messages.success(request, '프로필이 업데이트 되었습니다!')
            return redirect('user:mypage', username=username)
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'user/mypage_update.html', {'form': user_form, 'profileform': profile_form})


@login_required
def add_or_sub_follower(request, username):
    target = get_object_or_404(get_user_model(), username=username)
    target_profile = target.profile
    user_profile = request.user.profile

    if user_profile.follows.filter(id=target_profile.id).exists():
        user_profile.follows.remove(target_profile)
    else:
        user_profile.follows.add(target_profile)

    return redirect('user:index')


class UserList(ListView):
    model = get_user_model()
    template_name = 'user/user_list.html'
    context_object_name = 'users'
    paginate_by = 3

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return self.model.objects.none()

        query = self.request.GET.get('query', '')
        search_by = self.request.GET.get('search_by', 'ID')

        if query:
            if search_by == 'ID':
                return self.model.objects.filter(username__icontains=query)
            elif search_by == 'first_name':
                return self.model.objects.filter(Q(first_name__icontains=query) | Q(last_name__icontains=query))
            else:
                return self.model.objects.none()

    def get_context_data(self, **kwargs):
        if not self.request.user.is_authenticated:
            return self.model.objects.none()

        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query', '')
        context['search_by'] = self.request.GET.get('search_by', 'ID')

        return context


class FollowList(ListView):
    model = get_user_model()
    template_name = 'user/user_list.html'
    context_object_name = 'users'
    paginate_by = 3

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return self.model.objects.none()

        follows = self.request.user.profile.follows.all()
        usernames = [profile.user.username for profile in follows]
        return self.model.objects.filter(username__in=usernames)

b9/templates/user/follow_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if follows %}
    {% for follow in follows %}
    <ul>
        <li>{{follow}}</li>
    </ul>
    {% endfor %}
    {%else%}
    팔로우가 없습니다
    {% endif %}
</body>
</html>

b9/templates/user/index.html
{% extends 'base.html' %}

{% block title %}
    회원가입
{% endblock %}


{% block content %}

    <!-- Main -->
    <div id="main">
        <!-- 포스트 검색기능-->
        <ul class="search">
            <form method="GET" action="{% url 'post:post_searched' %}" name="flexForm" class="sh_search_home">
                <input type="text" name="query" placeholder="PostSearch" class="sh_head_search"
                       value="{{ request.GET.query }}">
                <button type="submit">Post Search</button>
            </form>
        </ul>
        <ul>
            <!-- Post -->
            {% for post in posts %}
                <article class="post">
                    <header>
                        <div class="title">
                            <h2>{{ post.title }}</h2>
                            {% if post.tags.all %}
                                {% for tag in post.tags.all %}
                                    <a style="font-size: small"
                                       href="{% url 'post:tagged_object_list' tag.name %}">
                                        <span> #{{ tag.name }}&nbsp; </span>
                                    </a>
                                {% endfor %}
                                -<a style="font-size: small"
                                    href="{% url 'post:tag_cloud' %}">TagCloud</a>
                            {% endif %}
                        </div>
                        <div class="meta">
                            <time class="published" datetime="{{ post.created_at }}">{{ post.created_at|timesince }}
                                전
                            </time>
                            <a href="{% url 'user:mypage' post.writer.username %}"><span class="name">{{ post.writer.last_name }} {{ post.writer.first_name }}</span></a>
                        </div>
                    </header>
                    {% if post.photo %}
                        <a href="{% url 'post:detail_post' post.id %}" class="image featured"><img src="{{ post.photo.url }}" alt=""/></a>
                    {% endif %}
                    <p>{{ post.post|safe }}</p>
                    <footer>
                        <ul class="actions">
                            <li><a href="{% url 'post:detail_post' post.id %}" class="button large">Continue Reading</a></li>
                        </ul>
                        <ul class="stats">
                            {% if post.writer_id == user.username %}
                                <li><a href="{% url 'post:post_update' post.id %}">수정</a></li>
                                <li><a href="{% url 'post:delete_post' post.id %}">삭제</a></li>
                            {% endif %}
                            {% if user in post.like_users.all %}
                                <li><a href="{% url 'post:toggle_like' post.id %}"
                                       class="icon solid fa-heart" style="color:#ff00a0">{{ post.like_count }}</a>
                                </li>
                            {% else %}
                                <li><a href="{% url 'post:toggle_like' post.id %}"
                                       class="icon solid fa-heart"
                                       style="color: rgba(160, 160, 160, 0.5);">{{ post.like_count }}</a></li>
                            {% endif %}
                            <li><a href="{% url 'post:detail_post' post.id %}" class="icon solid fa-comment"
                                   style="color: rgba(160, 160, 160, 0.5);">{{ post.comment_count }}</a>
                            </li>
                        </ul>
                    </footer>
                </article>
            {% endfor %}
            <!-- Pagination -->
            <ul class="actions pagination">
                {% if posts.has_previous %}
                    <li><a href="?page={{ posts.previous_page_number }}" class="button large previous">Previous
                        Page</a></li>
                {% else %}
                    <li><a href=" " class="disabled button large previous">Previous Page</a></li>
                {% endif %}
                {% if posts.has_next %}
                    <li><a href="?page={{ posts.next_page_number }}" class="button large next">Next Page</a></li>
                {% else %}
                    <li><a href=" " class="disabled button large next">Next Page</a></li>
                {% endif %}
            </ul>
        </ul>
    </div>
    <!-- Sidebar -->
    <section id="sidebar">

        <!-- Intro -->
        <section id="intro">
            <header>
                <div style="border-bottom: 1px solid white; width: 45px; margin-top: 20px;"></div>
                <p class="sh_title_font" style="font-size: 45px; margin: 0px;">#<span class="G">C</span>ode</p>
                <p class="sh_title_font" style="font-size: 45px; margin-left: 85px; margin-bottom: 30px;">share</p>
                <p style="margin-bottom: 60px;">make by <a href="{% url 'user:b_9' %}">NBCamp[-1]</a></p>
                <a href="{% url 'post:post_create' %}" class="button large next">글 작성하기</a>
            </header>
        </section>

        <!-- Mini Posts -->
        <section>
            <div class="mini-posts">
                <!-- Mini Post -->
                {% if not request.user.authenticated %}
                    <p class="sh_title_font" style="font-size: 25px;"><span class="C">F</span>ollowing's Post List</p>
                    {% for post in followings %}
                        <article class="mini-post">
                            <header>
                                <h3><a href="{% url 'post:detail_post' post.id %}">{{ post.title }}</a></h3>
                                <time class="published" datetime="{{ post.created_at|date:'c' }}">
                                    {{ post.created_at|date:"F d, Y" }}</time>
                                <p style="font-size: 12px;">{{ post.writer }}</p>
                                {% if post.author.profile.profile_image %}
                                    <a href="#" class="author"><img src="{{ post.author.profile.profile_image.url }}"
                                                                    alt=""/></a>
                                {% endif %}
                            </header>
                            {% if post.photo %}
                                <a href="{% url 'post:detail_post' post.id %}" class="image"><img
                                        src="{{ post.photo.url }}"
                                        alt=""/></a>
                            {% endif %}
                        </article>
                        {% empty %}
                        <p class="sh_font_2">팔로잉한 사용자의 게시물이 없습니다.</p>
                    {% endfor %}
                {% else %}
                {% endif %}
            </div>
        </section>

        <!-- About -->



    </section>
    </div>
{% endblock %}

b9/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
    회원가입
{% endblock %}
{% block content %}

<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">로그인</button>
</form>

{% endblock %}

b9/templates/user/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    회원정보
{% endblock %}
{% block content %}

    <div class="container mt-4" style="max-width: 100%;">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h5>프로필 이미지</h5>
                    </div>
                    <div class="card-body">
                        {% if profile.profile_image %}
                            <img src="{{ profile.profile_image.url }}" alt="프로필 이미지"
                                 style="width: 100%; height: 280px ;object-fit: cover; object-position: center; background-color: transparent;">
                        {% else %}
                            <img src="{% static 'default_profile_image.jpg' %}" alt="기본 프로필 이미지"
                                 style="width: 100%; height: 280px; object-fit: cover; object-position: center; background-color: transparent;">
                        {% endif %}
                    </div>
                </div>
                <div class="card mt-4">
                    <div class="card-header">
                        <h5>회원 정보</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><strong>이름:</strong>
                            {{ user_profile.user.last_name }}{{ user_profile.user.first_name }}</li>
                        <li class="list-group-item"><strong>닉네임:</strong> {{ user_profile.user.username }}</li>
                        <li class="list-group-item"><strong>이메일:</strong> {{ user_profile.user.email }}</li>
                        <li class="list-group-item"><strong>가입일:</strong>
                            {{ user_profile.user.date_joined|date:'Y년 m월 d일'}}</li>
                    </ul>
                </div>
                {% if user.username == profile.user.username %}
                    <div class="card mt-4">
                            <div class="card-header">
                                <h5>회원 정보 수정</h5>
                            </div>
                            <div class="card-body">
                                <a type="button" class="button large" href="{% url 'user:mypage_update' user.username %}">수정하기</a>
                            </div>
                        </div>
                {% else %}
                    <div class="card mt-4">
                        <div class="card-header">
                            <h5>팔로우</h5>
                        </div>
                        <div class="card-body">

                            {% if is_following %}
                                <a type="button" class="button large"
                                   href="{% url 'user:following' user_profile.user.username %}">언팔로우</a>
                            {% else %}
                                <a type="button" class="button large"
                                   href="{% url 'user:following' user_profile.user.username %}">팔로우</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

            </div>
            <div class="col-md-7">
                <h1>Posting List</h1>
                <hr>
                {% for post in posts %}
                    <article class="post">
                        <header>
                            <div class="title">
                                <h2>{{ post.title }}</h2>
                                {% if post.tags.all %}
                                    {% for tag in post.tags.all %}
                                        <a style="font-size: small"
                                           href="{% url 'post:tagged_object_list' tag.name %}">
                                            <span> #{{ tag.name }} </span>
                                        </a>
                                    {% endfor %}
                                    -<a style="font-size: small"
                                        href="{% url 'post:tag_cloud' %}">TagCloud</a>
                                {% endif %}

                            </div>
                            <div class="meta">
                                <time class="published" datetime="{{ post.created_at }}">{{ post.created_at|timesince }}
                                    전
                                </time>
                                <a href="{% url 'user:mypage' post.writer.username %}" ><span class="name">{{ post.writer.last_name }} {{ post.writer.first_name }}</span>
                                </a></div>
                        </header>
                        {% if post.photo %}
                            <a href="{% url 'post:detail_post' post.id %}" class="image featured"><img src="{{ post.photo.url }}" alt=""/></a>
                        {% endif %}
                        <p>{{ post.post|safe }}</p>
                        <footer>
                            <ul class="actions">
                                <li><a href="{% url 'post:detail_post' post.id %}" class="button large">댓글 작성하기</a></li>
                            </ul>
                            <ul class="stats">
                                {% if user in post.like_users.all %}
                                    <li><a href="{% url 'post:toggle_like' post.id %}"
                                           class="icon solid fa-heart" style="color:#ff00a0">{{ post.like_count }}</a>
                                    </li>
                                {% else %}
                                    <li><a href="{% url 'post:toggle_like' post.id %}"
                                           class="icon solid fa-heart"
                                           style="color: rgba(160, 160, 160, 0.5);">{{ post.like_count }}</a></li>
                                {% endif %}
                                <li><a href="#" class="icon solid fa-comment"
                                       style="color: rgba(160, 160, 160, 0.5);">{{post.commentcount}}</a></li>
                            </ul>
                        </footer>
                    </article>
                {% endfor %}
                <!-- 페이지 선택 -->
                <hr>
                <ul class="actions pagination">
                    {#             만약 현재 페이지보다 이전 페이지가 존재 한다면#}
                    {% if posts.has_previous %}
                        {#                    바로 전 페이지로 이동하기#}
                        <li><a href="?page={{ posts.previous_page_number }}" class="button large previous">Previous
                            Page</a></li>
                    {% else %}
                        <li><a href=" " class="disabled button large previous">Previous Page</a></li>
                    {% endif %}
                    {#            만약 다음 페이지가 존재 한다면#}
                    {% if posts.has_next %}
                        {#                    바로 다음 페이지로 이동하기#}
                        <li><a href="?page={{ posts.next_page_number }}" class="button large next">Next Page</a></li>
                    {% else %}
                        <li><a href=" " class="disabled button large next">Next Page</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

b9/templates/user/signup.html
{% extends 'base.html' %}

{% block title %}
회원가입
{% endblock %}


{% block content %}

<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">로그인</button>
</form>

{% endblock %}

b9/templates/user/user.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if request.user.is_authenticated %}
        <h1>Hello {{request.user.username}} </h1>
        <a href="{% url 'user:logout' %}">로그아웃</a>
    {% else %}
        <a href="{% url 'user:login' %}">로그인</a>
        <a href="{% url 'user:signup' %}">회원가입</a>
    {% endif %}
    
    <form method="GET" action="{% url 'user:user_search' %}">
        <input type="text" name="query" placeholder="Search" value="{{ request.GET.query }}">
        <select name="search_by">
            <option value="ID" {% if request.GET.search_by == 'ID' %}selected{% endif %}>ID</option>
            <option value="first_name" {% if request.GET.search_by == 'first_name' %}selected{% endif %}>이름</option>
        </select>
        <button type="submit">Search</button>
    </form>

</body>
</html>