b9/b9/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('user.urls')),
    path('', include('post.urls')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

b9/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path("", views.home, name='codeshare'),
    path("index", views.index, name='index'),
    path("NBcamp[-1]/", views.b_9, name='b_9'),
    path("signup/", views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('follows/', views.FollowList.as_view(), name='follow'),
    path('@<str:username>/follow/', views.add_or_sub_follower, name='following'),
    path('@<str:username>/update/', views.user_mypage_update, name='mypage_update'),
    path('@<str:username>/', views.user_mypage, name='mypage'),
    path('search/', views.UserList.as_view(), name='search'),

]

b9/templates/Codeshare.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <title>Cordshare</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'assets/css/sh_home.css' %}"/>

    <style>
        html, body, div, span, applet, object,
        iframe, h1, h2, h3, h4, h5, h6, p, blockquote,
        pre, a, abbr, acronym, address, big, cite,
        code, del, dfn, em, img, ins, kbd, q, s, samp,
        small, strike, strong, sub, sup, tt, var, b,
        u, i, center, dl, dt, dd, ol, ul, li, fieldset,
        form, label, legend, table, caption, tbody,
        tfoot, thead, tr, th, td, article, aside,
        canvas, details, embed, figure, figcaption,
        footer, header, hgroup, menu, nav, output, ruby,
        section, summary, time, mark, audio, video {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 100%;
            font: inherit;
            vertical-align: baseline;
        }

        article, aside, details, figcaption, figure,
        footer, header, hgroup, menu, nav, section {
            display: block;
        }

        body {
            line-height: 1;
        }

        ol, ul {
            list-style: none;
        }

        blockquote, q {
            quotes: none;
        }

        blockquote:before, blockquote:after, q:before, q:after {
            content: '';
            content: none;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        body {
            -webkit-text-size-adjust: none;
        }

        mark {
            background-color: transparent;
            color: inherit;
        }

        input::-moz-focus-inner {
            border: 0;
            padding: 0;
        }

        input, select, textarea {
            -moz-appearance: none;
            -webkit-appearance: none;
            -ms-appearance: none;
            appearance: none;
        }

        /* Basic */

        @-ms-viewport {
            width: sdevice-width;
        }

        body {
            -ms-overflow-style: scrollbar;
        }

        @media screen and (max-width: 480px) {

            html, body {
                min-width: 320px;
            }

        }

        html {
            box-sizing: border-box;
        }

        *, *:before, *:after {
            box-sizing: inherit;
        }

        body.is-preload *, body.is-preload *:before, body.is-preload *:after {
            -moz-animation: none !important;
            -webkit-animation: none !important;
            -ms-animation: none !important;
            animation: none !important;
            -moz-transition: none !important;
            -webkit-transition: none !important;
            -ms-transition: none !important;
            transition: none !important;
        }

        body {
            background-image: url("{% static 'images/cordshare_background.png'%}");
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            overflow: hidden;
            color: white;
        }

        a {
            color: white;
            text-decoration: none;
        }

        a:hover {
            color: inherit;
        }

        input {
            background-color: transparent;
            border-color: transparent;
            border-bottom: 1px solid white;
            caret-color: transparent;
            width: 400px;
            padding-bottom: 2px;
        }

        input:focus-visible {
            outline: transparent;
        }

        input::selection {
            background-color: transparent;
        }

    </style>

</head>

<body>
{% block content %}
    <div class="container_f">
    <div class="head">
        <div class="top">
            <a href="{% url 'user:index' %}" class="btn_home_margin">
                <p class="sh_title_font btn_home"><span class="C">H</span>ome</p>
            </a>
        </div>
    </div>
    <div class="middle">
        <div class="box_title">
            <div class="CS_line"></div>
            <p class="sh_title_font CS_code">#<span class="G">C</span>ode</p>
            <p class="sh_title_font CS_share">share</p>
        </div>
        <div class="box_login">
            <form method="post" action="{% url 'user:login' %}">
                {% csrf_token %}
                <div class="in">
                    <p class="sh_title_font idpw">ID</p>
                    <input type="text" class="form-control sh_font_2 sh_select_none no-select" id="username"
                           name="username">
                </div>
                <div class="in">
                    <p class="sh_title_font idpw">PW</p>
                    <input type="password" class="form-control sh_font_2 sh_select_none no-select" id="password"
                           name="password">
                </div>
                <div class="btn_log_in_up">
                    <button type="submit" class="login_btn"><p class="sh_title_font btn_col C">Login</p></button>
                    <a href="{% url 'user:signup' %}"><p class="sh_title_font btn_col G">Signup</p></a>
                </div>
            </form>
        </div>
    </div>
    <div class="base">
    </div>
{% endblock %}
</div>

</body>

</html>

b9/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>

    <title>Codeshare</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'django_summernote/summernote.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Anek+Devanagari:wght@100;200;300;400;500;600;700;800&display=swap');

        /* --------------------------------------------- */

        /* 1. home.html의 #Codeshare 메인폰트입니다*/
        .sh_title_font {
            font-family: 'Abril Fatface', cursive;
        }

            /*2. 유저의 사용 폰트 테스트 1번*/
        .sh_font_1 {
            font-family: 'Poppins', sans-serif;
            font-style: italic;
        }

        /*font-weigth: 100, 200, 300, 400, 500, 600, 700, 800, 900,*/
        /*font-style: lialic*/

        /*3. 유저의 사용 폰트 테스트 2번*/
        .sh_font_2 {
            font-family: 'Anek Devanagari', sans-serif;
        }

        /*!*font-weigth: 100, 200, 300, 400, 500, 600, 700, 800, 900,*!*/

        /* --------------------------------------------- */

        .G {
            color: #007C32;
        }

        .C {
            color: #F3CB27;
        }

        .title-center {
            text-align: center;
            margin-top: 50px;
        }

        .wrap {
            width: 400px;
            margin: 0 auto;
        }

        .form-area {
            margin-top: 25px;
        }

        .timeline-container {
            margin-top: 25px
        }
    </style>


</head>

<body class="is-preload">
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
    {% endif %}

<!-- Wrapper -->
<div id="wrapper">
    <!-- Header -->
    <header id="header">
        <!-- title -->
        <h1 class="sh_title_font"><a href="{% url 'user:index' %}"><span class=G>C</span>ode share</a></h1>
        <nav class="links">
            {% if not user.is_authenticated %}
                <ul>
                    <li><a href="{% url 'user:login' %}">Sign In</a></li>
                    <li><a href="{% url 'user:signup' %}">Sign Up</a></li>
                </ul>
            {% else %}
            <ul>
                <li><a href="{% url 'user:mypage' username=user.username %}">{{ user.username }} 님 반갑습니다!</a></li>
                <li><a href="{% url 'user:index' %}">Post</a></li>
                <li><a href="{% url 'user:mypage' user.username %}"> Mypage</a></li>
                <li><a href="{% url 'user:logout' %}">Logout</a></li>
            </ul>
            {% endif %}
        </nav>
        <nav class="main">
            <ul class="search">
                <form method="GET" action="{% url 'user:search' %}" name="flexForm">
                    <li>
                        <select name="search_by">
                            <option value="ID" {% if request.GET.search_by == 'ID' %}selected{% endif %}>ID</option>
                            <option value="first_name"
                                    {% if request.GET.search_by == 'first_name' %}selected{% endif %}>
                                이름
                            </option>
                        </select>
                    </li>
                    <li>
                        <input type="text" name="query" placeholder="Search" value="{{ request.GET.query }}">
                    </li>
                    <li>
                        <button type="submit">Search</button>
                    </li>
                    </form> 
                </li>
            </ul>
        </nav>
    </header>

 

    {% block content %}

    {% endblock %}
</div>
    <div class="container">
        <!-- Footer -->
        <footer>
            <ul class="icons">
                <li><a href="https://spartacodingclub.kr/" >SpartaCodingClub</a></li>
                <li><a href="{% url 'user:b_9' %}" >NBCamp[-1]</a></li>
            </ul>
            <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a
                    href="http://unsplash.com">Unsplash</a>.</p>
        </footer>
    </div>
</div>

<!-- Scripts -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/browser.min.js' %}"></script>
<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
<script src="{% static 'assets/js/util.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>